--------------------------------------------------------------------------------
-- 1. BAW database (BPMDB)
create database <BAW_INSTANCE1_DB_NAME> automatic storage yes using codeset UTF-8 territory US pagesize 32768;
-- connect to the created database:
connect to <BAW_INSTANCE1_DB_NAME>;
-- A user temporary tablespace is required to support stored procedures in BPM.
CREATE USER TEMPORARY TABLESPACE USRTMPSPC1;
UPDATE DB CFG FOR <BAW_INSTANCE1_DB_NAME> USING LOGFILSIZ 16384 DEFERRED;
UPDATE DB CFG FOR <BAW_INSTANCE1_DB_NAME> USING LOGSECOND 64 IMMEDIATE;
-- The following grant is used for databases without enhanced security.
-- For more information, review the IBM Documentation for Enhancing Security for Db2.
grant dbadm on database to user <DB_USER>;
connect reset;

--------------------------------------------------------------------------------
-- 2. Workstream services database
create database <BAW_INSTANCE2_DB_NAME> automatic storage yes using codeset UTF-8 territory US pagesize 32768;
-- connect to the created database:
connect to <BAW_INSTANCE2_DB_NAME>;
-- A user temporary tablespace is required to support stored procedures in BPM.
CREATE USER TEMPORARY TABLESPACE USRTMPSPC1;
UPDATE DB CFG FOR <BAW_INSTANCE2_DB_NAME> USING LOGFILSIZ 16384 DEFERRED;
UPDATE DB CFG FOR <BAW_INSTANCE2_DB_NAME> USING LOGSECOND 64 IMMEDIATE;
-- The following grant is used for databases without enhanced security.
-- For more information, review the IBM Knowledge Center for Enhancing Security for Db2.
grant dbadm on database to user <DB_USER>;
connect reset;

--------------------------------------------------------------------------------
-- 3. App Engine (AAEDB)
create database APP_ENGINE_DB_NAME automatic storage yes using codeset UTF-8 territory US pagesize 32768;

-- connect to the created database:
connect to APP_ENGINE_DB_NAME;

-- Create bufferpool and tablespaces
CREATE BUFFERPOOL DBASBBP IMMEDIATE SIZE 1024 PAGESIZE 32K;
CREATE REGULAR TABLESPACE APPENG_TS PAGESIZE 32 K MANAGED BY AUTOMATIC STORAGE DROPPED TABLE RECOVERY ON BUFFERPOOL DBASBBP;
CREATE USER TEMPORARY TABLESPACE APPENG_TEMP_TS PAGESIZE 32 K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL DBASBBP;

-- grant access rights to the tablespaces
GRANT USE OF TABLESPACE APPENG_TS TO user APP_ENGINE_DB_USER_NAME;
GRANT USE OF TABLESPACE APPENG_TEMP_TS TO user APP_ENGINE_DB_USER_NAME;

-- The following grant is used for databases without enhanced security.
-- For more information, review the IBM documentation for enhancing security for DB2.
grant dbadm on database to user APP_ENGINE_DB_USER_NAME;

connect reset;

--------------------------------------------------------------------------------
-- 4. DOCS (BAWDOCS), 5. TOS (BAWTOS), 6. DOS (BAWDOS), and 7. AEOS (AEOSDB)

--------------------------------------------------------------------------------
-- 8. BAN database
-- IBM CONTENT NAVIGATOR DB2 SQL Script
--
-- Tip: If you plan to create a database on a remote instance,
-- ensure that the @ECMClient_NODENAME@ node has been
-- cataloged and remove the comment code from the following line:
-- ATTACH TO @ECMClient_NODENAME@;

CREATE database @ECMClient_DBNAME@ AUTOMATIC STORAGE YES ON
@ECMClient_DBDRIVE@ DBPATH on @ECMClient_DBDRIVE@
USING CODESET UTF-8 TERRITORY @ECMClient_TERRITORY@ COLLATE USING SYSTEM;

--------------------------------------------------------------------------------
-- 9. UMS database (UMSDB)
db2 create database UMSDB automatic storage yes using codeset UTF-8 territory US pagesize 32768

--------------------------------------------------------------------------------
-- 10. ICN / BAN (ICNDB)
-- IBM CONTENT NAVIGATOR DB2 SQL Script
--
-- Tip: If you plan to create a database on a remote instance,
-- ensure that the @ECMClient_NODENAME@ node has been
-- cataloged and remove the comment code from the following line:
-- ATTACH TO @ECMClient_NODENAME@;

CREATE database @ECMClient_DBNAME@ AUTOMATIC STORAGE YES ON
@ECMClient_DBDRIVE@ DBPATH on @ECMClient_DBDRIVE@
USING CODESET UTF-8 TERRITORY @ECMClient_TERRITORY@ COLLATE USING SYSTEM;

--------------------------------------------------------------------------------
-- 11. BAS
create database basdb automatic storage yes using codeset UTF-8 territory US pagesize 32768;

-- connect to the created database:
connect to basdb;

-- A user temporary tablespace is required to support stored procedures in BPM.
CREATE USER TEMPORARY TABLESPACE USRTMPSPC1;

UPDATE DB CFG FOR basdb USING LOGFILSIZ 16384 DEFERRED;
UPDATE DB CFG FOR basdb USING LOGSECOND 64 IMMEDIATE;

-- The following grant is used for databases without enhanced security.
-- For more information, review the IBM documentation for enhancing security for DB2.
grant dbadm on database to user db2inst1;

connect reset;

--------------------------------------------------------------------------------
-- 12. Base Content Analyzer Database BASECA
CREATE DATABASE BASECA AUTOMATIC STORAGE YES USING CODESET UTF-8 TERRITORY DEFAULT COLLATE USING SYSTEM PAGESIZE 32768;

CONNECT TO BASECA ;

GRANT CONNECT,DATAACCESS ON DATABASE TO USER db2inst1 ;

GRANT USE OF TABLESPACE USERSPACE1 TO USER db2inst1 ;

CONNECT RESET;


--------------------------------------------------------------------------------
-- 13. Content Analyzer Project Database 1 PROJ1DB
CREATE DATABASE PROJ1DB AUTOMATIC STORAGE YES USING CODESET UTF-8 TERRITORY DEFAULT COLLATE USING SYSTEM PAGESIZE 32768;

UPDATE DATABASE CONFIGURATION FOR PROJ1DB USING LOGFILSIZ 7500 ;
UPDATE DATABASE CONFIGURATION FOR PROJ1DB USING LOGPRIMARY 15;

UPDATE DATABASE CONFIGURATION FOR PROJ1DB USING APPLHEAPSZ 2560;
UPDATE DATABASE CONFIGURATION FOR PROJ1DB USING STMTHEAP 8192;

CONNECT TO PROJ1DB ;
--DROP TABLESPACE USERSPACE1 ;
CREATE Bufferpool PROJ1DBBP IMMEDIATE SIZE -1 PAGESIZE 32K ;
CREATE Bufferpool PROJ1DBTEMPBP IMMEDIATE SIZE -1 PAGESIZE 32K ;
CREATE Bufferpool PROJ1DBSYSBP IMMEDIATE SIZE -1 PAGESIZE 32K ;
CONNECT RESET ;

CONNECT TO PROJ1DB;
CREATE LARGE TABLESPACE PROJ1DBDATA PAGESIZE 32K BUFFERPOOL PROJ1DBBP ;
CREATE USER TEMPORARY TABLESPACE PROJ1TEMP PAGESIZE 32K BUFFERPOOL PROJ1DBTEMPBP ;
CREATE SYSTEM TEMPORARY TABLESPACE PROJ1SYS PAGESIZE 32K BUFFERPOOL PROJ1DBSYSBP;
CONNECT RESET ;

CONNECT TO PROJ1DB;
GRANT CONNECT,DATAACCESS,CREATETAB ON DATABASE TO USER db2inst1 ;
GRANT USE OF TABLESPACE PROJ1DBDATA TO user db2inst1 ;
GRANT USE OF TABLESPACE PROJ1TEMP TO user db2inst1 ;

REVOKE SELECT ON TABLE SYSCAT.COLAUTH  FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.CONTROLS FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.DBAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.INDEXAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.LIBRARYAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.MODULEAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.PACKAGEAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.PASSTHRUAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.ROLEAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.ROUTINEAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.SCHEMAAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.SECURITYLABELACCESS FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.SECURITYLABELCOMPONENTELEMENTS FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.SECURITYLABELCOMPONENTS FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.SECURITYLABELS FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.SECURITYPOLICIES FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.SECURITYPOLICYCOMPONENTRULES FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.SECURITYPOLICYEXEMPTIONS FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.SEQUENCEAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.SURROGATEAUTHIDS FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.TABAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.TBSPACEAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.VARIABLEAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.WORKLOADAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.XSROBJECTAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SQLCOLPRIVILEGES FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SQLTABLEPRIVILEGES FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBMADM.AUTHORIZATIONIDS FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBMADM.OBJECTOWNERS FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBMADM.PRIVILEGES FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSCOLAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSCONTROLS FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSDBAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSINDEXAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSLIBRARYAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSMODULEAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSPASSTHRUAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSPLANAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSROLEAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSROUTINEAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSSCHEMAAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSSECURITYLABELACCESS FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSSECURITYLABELCOMPONENTELEMENTS FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSSECURITYLABELCOMPONENTS FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSSECURITYLABELS FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSSECURITYPOLICIES FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSSECURITYPOLICYCOMPONENTRULES FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSSECURITYPOLICYEXEMPTIONS FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSSEQUENCEAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSSURROGATEAUTHIDS FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSTABAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSTBSPACEAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSUSERAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSVARIABLEAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSWORKLOADAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSXSROBJECTAUTH FROM PUBLIC ;

CONNECT RESET;

--------------------------------------------------------------------------------
-- 14. Content Analyzer Project Database 2 PROJ2DB
CREATE DATABASE PROJ2DB AUTOMATIC STORAGE YES USING CODESET UTF-8 TERRITORY DEFAULT COLLATE USING SYSTEM PAGESIZE 32768;

UPDATE DATABASE CONFIGURATION FOR PROJ2DB USING LOGFILSIZ 7500 ;
UPDATE DATABASE CONFIGURATION FOR PROJ2DB USING LOGPRIMARY 15;

UPDATE DATABASE CONFIGURATION FOR PROJ2DB USING APPLHEAPSZ 2560;
UPDATE DATABASE CONFIGURATION FOR PROJ2DB USING STMTHEAP 8192;

CONNECT TO PROJ2DB ;
-- DROP TABLESPACE USERSPACE1 ;
CREATE Bufferpool PROJ2DBBP IMMEDIATE SIZE -1 PAGESIZE 32K ;
CREATE Bufferpool PROJ2DBTEMPBP IMMEDIATE SIZE -1 PAGESIZE 32K ;
CREATE Bufferpool PROJ2DBSYSBP IMMEDIATE SIZE -1 PAGESIZE 32K ;
CONNECT RESET ;

CONNECT TO PROJ2DB;
CREATE LARGE TABLESPACE PROJ2DBDATA PAGESIZE 32K BUFFERPOOL PROJ2DBBP ;
CREATE USER TEMPORARY TABLESPACE PROJ2TEMP PAGESIZE 32K BUFFERPOOL PROJ2DBTEMPBP ;
CREATE SYSTEM TEMPORARY TABLESPACE PROJ2SYS PAGESIZE 32K BUFFERPOOL PROJ2DBSYSBP;
CONNECT RESET ;

CONNECT TO PROJ2DB;
GRANT CONNECT,DATAACCESS,CREATETAB ON DATABASE TO USER db2inst1 ;
GRANT USE OF TABLESPACE PROJ2DBDATA TO user db2inst1 ;
GRANT USE OF TABLESPACE PROJ2TEMP TO user db2inst1 ;

REVOKE SELECT ON TABLE SYSCAT.COLAUTH  FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.CONTROLS FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.DBAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.INDEXAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.LIBRARYAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.MODULEAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.PACKAGEAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.PASSTHRUAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.ROLEAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.ROUTINEAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.SCHEMAAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.SECURITYLABELACCESS FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.SECURITYLABELCOMPONENTELEMENTS FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.SECURITYLABELCOMPONENTS FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.SECURITYLABELS FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.SECURITYPOLICIES FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.SECURITYPOLICYCOMPONENTRULES FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.SECURITYPOLICYEXEMPTIONS FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.SEQUENCEAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.SURROGATEAUTHIDS FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.TABAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.TBSPACEAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.VARIABLEAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.WORKLOADAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSCAT.XSROBJECTAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SQLCOLPRIVILEGES FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SQLTABLEPRIVILEGES FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBMADM.AUTHORIZATIONIDS FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBMADM.OBJECTOWNERS FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBMADM.PRIVILEGES FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSCOLAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSCONTROLS FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSDBAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSINDEXAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSLIBRARYAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSMODULEAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSPASSTHRUAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSPLANAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSROLEAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSROUTINEAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSSCHEMAAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSSECURITYLABELACCESS FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSSECURITYLABELCOMPONENTELEMENTS FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSSECURITYLABELCOMPONENTS FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSSECURITYLABELS FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSSECURITYPOLICIES FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSSECURITYPOLICYCOMPONENTRULES FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSSECURITYPOLICYEXEMPTIONS FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSSEQUENCEAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSSURROGATEAUTHIDS FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSTABAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSTBSPACEAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSUSERAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSVARIABLEAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSWORKLOADAUTH FROM PUBLIC ;
REVOKE SELECT ON TABLE SYSIBM.SYSXSROBJECTAUTH FROM PUBLIC ;

CONNECT RESET;

--------------------------------------------------------------------------------
-- 15. Operational Decision Manager - ODMDB
CREATE DATABASE ODMDB AUTOMATIC STORAGE YES USING CODESET UTF-8 TERRITORY DEFAULT COLLATE USING SYSTEM PAGESIZE 32768;

CONNECT TO ODMDB;

CREATE BUFFERPOOL BP32K SIZE 2000 PAGESIZE 32K;
CREATE TABLESPACE RESDWTS PAGESIZE 32K BUFFERPOOL BP32K;
CREATE SYSTEM TEMPORARY TABLESPACE RESDWTMPTS PAGESIZE 32K BUFFERPOOL BP32K;
