kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cp4a-shared-log-pvc
  namespace: <CP4BANAMESPACE>
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: cp4a-shared-log-pv
  volumeMode: Filesystem
