apiVersion: v1
kind: PersistentVolume
metadata:
  name: cp4a-shared-log-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: <NFSSERVERLOGSPATH>
    server: <NFSSERVER>
  persistentVolumeReclaimPolicy: Delete
  volumeMode: Filesystem
