apiVersion: db2u.databases.ibm.com/v1
kind: Db2uCluster
metadata:
  name: db2ucluster-cp4ba
  labels:
    app.kubernetes.io/instance: db2u-operator
    app.kubernetes.io/managed-by: Db2U-Team
    app.kubernetes.io/name: db2u-operator
  namespace: cp4ba
spec:
  account:
    imagePullSecrets:
      - admin.registrykey
    privileged: true
  environment:
    database:
      name: ODMDB
      settings:
        codeset: UTF-8
        collation: IDENTITY
        dftPageSize: '32768'
        dftTableOrg: COLUMN
        encrypt: 'YES'
        territory: US
    dbType: db2oltp
    instance:
      password: cicdtest
      dbmConfig:
        NUMDB: "20"
  license:
    accept: true
  podConfig:
    db2u:
      resource:
        db2u:
          requests:
            cpu: 2
            memory: 8Gi
          limits:
            cpu: 2
            memory: 8Gi
  size: 1
  storage:
    - name: meta
      type: "create"
      spec:
        storageClassName: "ocs-storagecluster-cephfs"
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 10Gi
    - name: data
      type: "create"
      spec:
        storageClassName: "ocs-storagecluster-ceph-rbd"
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
  version: "11.5.6.0-cn1"
  addOns:
    rest:
      enabled: false
    graph:
      enabled: false
