apiVersion: db2u.databases.ibm.com/v1
kind: Db2uCluster
metadata:
  name: db2ucluster-cp4ba
  namespace: cp4ba
spec:
  account:
    imagePullSecrets:
      - admin.registrykey
    privileged: true
  environment:
    database:
      name: CP4ADB
      settings:
        codeset: UTF-8
        collation: IDENTITY
        dftPageSize: '32768'
        dftTableOrg: COLUMN
        encrypt: 'YES'
        territory: US
    dbType: db2oltp
    instance:
      password: 'cicdtest'
      dbmConfig:
        NUMDB: "20"
  license:
    accept: true
  podConfig:
    db2u:
      resource:
        db2u:
          limits:
            cpu: 1
            memory: 8Gi
          requests:
            cpu: 1
            memory: 8Gi
  size: 1
  storage:
    - name: meta
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 10Gi
        storageClassName: 'nfs-managed-storage'
      type: create
    - name: data
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 100Gi
        storageClassName: 'nfs-managed-storage'
      type: create
  version: 11.5.6.0
