apiVersion: db2u.databases.ibm.com/v1
kind: Db2uCluster
metadata:
  name: db2ucluster-sample
  namespace: cp4ba
spec:
  license:
    accept: true
  account:
    imagePullSecrets:
    - ibm-registry
  addOns:
    graph:
      enabled: false
    rest:
      enabled: false
  advOpts:
    db2SecurityPlugin: cloud_gss_plugin
  environment:
    database:
      dbConfig:
        LOGFILSIZ: "2000"
      name: sampledb
    dbType: db2oltp
    instance:
      dbmConfig:
        SRVCON_PW_PLUGIN: IBMIAMauthpwfile
        group_plugin: IBMIAMauthgroup
        srvcon_auth: GSS_SERVER_ENCRYPT
        srvcon_gssplugin_list: IBMIAMauth
      password: 'cicdtest'
      registry:
        DB2_FMP_RUN_AS_CONNECTED_USER: "NO"
        DB2AUTH: OSAUTHDB,ALLOW_LOCAL_FALLBACK,PLUGIN_AUTO_RELOAD
        DB2_COMPATIBILITY_VECTOR: ORA
    ldap:
      enabled: false
    mln:
      total: 1
  podConfig:
    db2u:
      resource:
        db2u:
          limits:
            cpu: 2
            memory: 4Gi
  size: 1
  storage:
  - name: meta
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 20Gi
      storageClassName: ocs-storagecluster-cephfs
    type: create
  - name: data
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 80Gi
      storageClassName: ocs-storagecluster-cephfs
    type: create
  - name: backup
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 100Gi
      storageClassName: ocs-storagecluster-cephfs
    type: create
  version: 11.5.6.0
