kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: operator-shared-pvc
  namespace: cp4ba
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-cephfs
